name: Vuepress Deploy CI

on:
  push:
    branches:
    - master
    - test

jobs:
  build:
    name: CI&CD # 此任务（job）的名字
    runs-on: ubuntu-latest

    steps: # 切换分支到master
    - uses: actions/checkout@v1
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x # 启用node环境
      uses: actions/setup-node@v2.1.4 # 使用node环境
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npm.taobao.org'

    - name: Cache node modules # 缓存依赖包
        id: cache # 缓存id
        uses: actions/cache@v2.1.4
        env:
          cache-name: cache-node-modules # 缓存名字
        with:
          path: node_modules # 缓存路径
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }} # 缓存标识

    - name: Install npm dependencies # 安装依赖
      if: steps.cache.outputs.cache-hit != 'true' # 如果没有缓存的话
      run: npm install # 安装依赖

    - name: Run build task # 构建
      run: npm run build --if-present

 
    - name: Deploy File to Tencent Server
      uses: HenryWong-fe/ssh-deploy@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avz --delete"
        SOURCE: "docs/.vuepress/dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        DEPLOY_KEY_NAME: "id_rsa"    
        
    - name: upload-artifact
        uses: actions/upload-artifact@v2 #共享或保存action过程中产生的文件
        with:
          name: static_web_file
          path: ./docs/.vuepress/dist/ # or path/to/artifact