name: Vuepress Deploy CI

on:
  push:
    branches:
    - main
    - test

jobs:
  build:
    name: CI&CD # 此任务（job）的名字
    runs-on: ubuntu-latest

    steps: # 切换分支到master
    - uses: actions/checkout@master
      with:
        fetch-depth: 2

    - name: Use Node.js 12.x # 启用node环境
      uses: actions/setup-node@v2.1.4 # 使用node环境
      with:
        node-version: '12.x'

    - name: Install npm dependencies # 安装依赖
      run: npm install # 安装依赖

    - name: Run build task # 构建
      run: npm run docs:build

    - name: Deploy File to Tencent Server
      uses: easingthemes/ssh-deploy@v2.1.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SOURCE: 'public'
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: '/root/web/vuepress-blog'